###
GET https://google.com

###

###
GET http://localhost:3000/about

###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/10

###
DELETE http://localhost:3000/api/v1/users/1

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "first": "Wario",
    "last": "Spegelli",
    "email": "goldberg@newpaltz.edu",
    "handle": "wariowareofficial2",
    "region": 1,
    "admin": false
}